# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_test_metrics.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/05_test_metrics.ipynb 1
import torch
import torch.nn.functional as f

from fastcore.utils import *
from ..core import *
from ..metrics import accuracy

import pytest
