# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03a_activations.ipynb.

# %% auto 0
__all__ = ['relu']

# %% ../nbs/03a_activations.ipynb 3
import torch
import numpy as np

# %% ../nbs/03a_activations.ipynb 4
from fastcore.utils import *
from .core import *

# %% ../nbs/03a_activations.ipynb 7
def relu(x):
    return x.clamp_min(0.) - 0.5
