# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['A', 'B', 'test_near_zero']

# %% ../nbs/00_core.ipynb 2
from torch import tensor
import torch

from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/00_core.ipynb 5
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# %% ../nbs/00_core.ipynb 7
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# %% ../nbs/00_core.ipynb 9
def test_near_zero(a, tol=1e-3):
    assert a.abs()<tol, f"Near zero: {a}"
