# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['PATH_DIR', 'A', 'B', 'check_near_zero', 'is_same_shape_tensor', 'is_near_tensor']

# %% ../nbs/00_core.ipynb 2
import os

from torch import tensor
import torch

from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/00_core.ipynb 5
# TODO: Add relative path
# PATH_DIR = os.path.dirname(__file__)

PATH_DIR = "/Users/study/DATA/projects/data-science/deep-learning/tinypytorch-draft"

# %% ../nbs/00_core.ipynb 7
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# %% ../nbs/00_core.ipynb 9
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# %% ../nbs/00_core.ipynb 12
def check_near_zero(a, tol=1e-3):
    assert a.abs()<tol, f"Near zero: {a}"

# %% ../nbs/00_core.ipynb 13
def is_same_shape_tensor(a, b):
    assert a.shape == b.shape

# %% ../nbs/00_core.ipynb 14
def is_near_tensor(a, b):
    return torch.allclose(a, b, rtol=1e-3, atol=1e-5)
