# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_loss.ipynb.

# %% auto 0
__all__ = ['softmax', 'log_softmax', 'negative_log_likelihood']

# %% ../nbs/03_loss.ipynb 3
from fastcore.utils import *
import numpy as np

# %% ../nbs/03_loss.ipynb 4
from .core import *

# %% ../nbs/03_loss.ipynb 12
def softmax(x):
    pass
    #return np.exp(x) / np.exp(x).sum()

# %% ../nbs/03_loss.ipynb 16
def log_softmax(x):
    #sm = softmax(x)
    #return np.log(sm)
    pass

# %% ../nbs/03_loss.ipynb 19
def negative_log_likelihood(
    input, # the probabilities predicted for each label
    target: 'the index of the correct label'):
    pass
