# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02a_matmul.ipynb.

# %% auto 0
__all__ = ['matmul']

# %% ../nbs/02a_matmul.ipynb 3
from fastcore.utils import *

# %% ../nbs/02a_matmul.ipynb 5
# TODO: understand this
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c
