# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_metrics.ipynb.

# %% auto 0
__all__ = ['accuracy']

# %% ../nbs/05_metrics.ipynb 2
import torch
from fastcore.utils import *
from .core import *

# %% ../nbs/05_metrics.ipynb 5
def accuracy(out: "output", yb: "y batch"):
    return (torch.argmax(out, dim=1) == yb).float().mean()
